# fly.toml app configuration file generated for multi-modal-starter-kit on 2024-02-22T17:49:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'multi-modal-starter-kit'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
